"use client";
import { useEffect, useState } from "react";

type Lang = 'TR' | 'EN' | 'DE' | 'FR';
const box = {maxWidth:750,margin:'60px auto',background:'#171c2d',borderRadius:22,padding:36,color:'#ffe18d',boxShadow:'0 10px 30px #0007'} as const;
const body = {color:'#eaeaea',fontWeight:600,marginBottom:28,fontSize:'1.07rem'} as const;

const content = {
  TR: <div style={box}><h1 style={{fontWeight:800,fontSize:'2.1rem',marginBottom:18}}>MESAFELİ SATIŞ SÖZLEŞMESİ</h1><div style={body}><ol style={{marginLeft:18}}><li><b>TARAFLAR</b><br/>Satıcı: Şule Elmas, Türkiye/Antalya, suleelmas13@gmail.com, veritasai.com.<br/>Alıcı: Veritas Q-AI platformuna üye olan ve hizmet satın alan kişidir.</li><li><b>SÖZLEŞMENİN KONUSU</b><br/>Bu sözleşme, veritasai.com üzerinden sunulan Yapay Zeka Tabanlı Hukuki Analiz Hizmeti’nin satışı ve dijital teslimine ilişkin tarafların hak ve yükümlülüklerini düzenler.</li><li><b>HİZMET VE ÖDEME</b><br/>Seçilen pakete göre belirli sayıda veya sınırsız analiz hakkı sağlayan dijital üyelik sunulur. Satış bedeli sitede gösterilen fiyattır. Ödeme kredi/banka kartıyla Shopier veya Lemon Squeezy üzerinden yapılabilir.</li><li><b>İFA VE TESLİMAT</b><br/>Hizmet dijital içeriktir ve ödeme sonrası kullanıcı hesabına tanımlanır.</li><li><b>CAYMA HAKKI</b><br/>Dijital ve anında ifa edilen hizmetlerde uygulanabilecek cayma hakkı istisnaları geçerlidir. Ödeme öncesinde ilgili koşulların kullanıcı tarafından incelenmesi gerekir.</li><li><b>GENEL HÜKÜMLER</b><br/>Kullanıcı hizmetin niteliklerini, fiyatını ve teslim esaslarını kabul eder. Veritas Q-AI raporları avukatlık hizmeti veya kesin hukuki görüş değildir.</li><li><b>YETKİ</b><br/>Uyuşmazlıklarda yürürlükteki tüketici mevzuatı uyarınca görevli ve yetkili merciler uygulanır.</li><li><b>YÜRÜRLÜK</b><br/>Alıcı sipariş ve ödeme işlemini tamamladığında sözleşme koşullarını kabul etmiş sayılır.</li></ol></div></div>,
  EN: <div style={box}><h1 style={{fontWeight:800,fontSize:'2.1rem',marginBottom:18}}>DISTANCE SALES AGREEMENT</h1><div style={body}><ol style={{marginLeft:18}}><li><b>PARTIES</b><br/>Seller: Şule Elmas, Türkiye/Antalya, suleelmas13@gmail.com, veritasai.com.<br/>Buyer: The person registered on the Veritas Q-AI platform who purchases the service.</li><li><b>SUBJECT</b><br/>This Agreement governs the rights and obligations of the parties concerning the sale and digital delivery of the AI-Powered Legal Analysis Service offered through veritasai.com.</li><li><b>SERVICE AND PAYMENT</b><br/>The selected package provides a specified or unlimited number of analyses. The sales price is the price shown on the site. Payment may be made by credit/debit card through Shopier or Lemon Squeezy.</li><li><b>PERFORMANCE AND DELIVERY</b><br/>The service is digital content and is assigned to the user account after payment.</li><li><b>RIGHT OF WITHDRAWAL</b><br/>Exceptions applicable to instantly performed digital services may apply. Users should review the applicable conditions before payment.</li><li><b>GENERAL TERMS</b><br/>The user accepts the service characteristics, price and delivery terms. Veritas Q-AI reports are not legal representation or definitive legal advice.</li><li><b>JURISDICTION</b><br/>Competent consumer authorities and courts are determined under applicable consumer law.</li><li><b>ENTRY INTO FORCE</b><br/>The Buyer is deemed to accept the Agreement by completing the order and payment.</li></ol></div></div>,
  DE: <div style={box}><h1 style={{fontWeight:800,fontSize:'2.1rem',marginBottom:18}}>FERNABSATZVERTRAG</h1><div style={body}><ol style={{marginLeft:18}}><li><b>PARTEIEN</b><br/>Verkäuferin: Şule Elmas, Türkiye/Antalya, suleelmas13@gmail.com, veritasai.com.<br/>Käufer: Die auf der Veritas Q-AI-Plattform registrierte Person, die den Dienst erwirbt.</li><li><b>VERTRAGSGEGENSTAND</b><br/>Dieser Vertrag regelt die Rechte und Pflichten der Parteien im Zusammenhang mit dem Verkauf und der digitalen Bereitstellung des über veritasai.com angebotenen KI-gestützten Rechtsanalysedienstes.</li><li><b>DIENST UND ZAHLUNG</b><br/>Das gewählte Paket umfasst eine bestimmte oder unbegrenzte Zahl von Analysen. Der Verkaufspreis entspricht dem auf der Website angegebenen Preis. Die Zahlung kann per Kredit-/Debitkarte über Shopier oder Lemon Squeezy erfolgen.</li><li><b>LEISTUNG UND BEREITSTELLUNG</b><br/>Der Dienst ist digitaler Inhalt und wird nach Zahlung dem Benutzerkonto zugeordnet.</li><li><b>WIDERRUFSRECHT</b><br/>Für sofort erbrachte digitale Dienstleistungen können gesetzliche Ausnahmen vom Widerrufsrecht gelten. Die geltenden Bedingungen sollten vor der Zahlung geprüft werden.</li><li><b>ALLGEMEINE BESTIMMUNGEN</b><br/>Der Nutzer akzeptiert Leistungsmerkmale, Preis und Bereitstellungsbedingungen. Veritas Q-AI-Berichte stellen keine anwaltliche Vertretung oder verbindliche Rechtsberatung dar.</li><li><b>ZUSTÄNDIGKEIT</b><br/>Zuständige Verbraucherstellen und Gerichte bestimmen sich nach dem anwendbaren Verbraucherrecht.</li><li><b>INKRAFTTRETEN</b><br/>Mit Abschluss von Bestellung und Zahlung gilt der Vertrag als angenommen.</li></ol></div></div>,
  FR: <div style={box}><h1 style={{fontWeight:800,fontSize:'2.1rem',marginBottom:18}}>CONTRAT DE VENTE À DISTANCE</h1><div style={body}><ol style={{marginLeft:18}}><li><b>PARTIES</b><br/>Vendeuse : Şule Elmas, Türkiye/Antalya, suleelmas13@gmail.com, veritasai.com.<br/>Acheteur : La personne inscrite sur la plateforme Veritas Q-AI qui achète le service.</li><li><b>OBJET DU CONTRAT</b><br/>Le présent contrat régit les droits et obligations des parties concernant la vente et la fourniture numérique du service d’analyse juridique assisté par IA proposé via veritasai.com.</li><li><b>SERVICE ET PAIEMENT</b><br/>Le forfait choisi donne droit à un nombre déterminé ou illimité d’analyses. Le prix est celui affiché sur le site. Le paiement peut être effectué par carte bancaire via Shopier ou Lemon Squeezy.</li><li><b>EXÉCUTION ET LIVRAISON</b><br/>Le service constitue un contenu numérique et est attribué au compte utilisateur après le paiement.</li><li><b>DROIT DE RÉTRACTATION</b><br/>Des exceptions légales peuvent s’appliquer aux services numériques exécutés immédiatement. L’utilisateur doit consulter les conditions applicables avant le paiement.</li><li><b>DISPOSITIONS GÉNÉRALES</b><br/>L’utilisateur accepte les caractéristiques du service, son prix et ses modalités de fourniture. Les rapports Veritas Q-AI ne constituent ni une représentation par avocat ni un avis juridique définitif.</li><li><b>JURIDICTION</b><br/>Les autorités de consommation et juridictions compétentes sont déterminées par le droit de la consommation applicable.</li><li><b>ENTRÉE EN VIGUEUR</b><br/>L’Acheteur est réputé accepter le contrat en finalisant la commande et le paiement.</li></ol></div></div>
} as const;

export default function DistanceAgreement() {
  const [lang, setLang] = useState<Lang>('EN');
  useEffect(() => {
    const saved = typeof window !== 'undefined' ? (localStorage.getItem('language') || localStorage.getItem('lang') || navigator.language.slice(0,2).toUpperCase()) : 'EN';
    setLang(saved === 'TR' || saved === 'DE' || saved === 'FR' ? saved : 'EN');
  }, []);
  return content[lang];
}
