"use client";
import React, { useState, useEffect, useRef } from 'react';
import PricingCard from "./components/PricingCard";
import { createBrowserClient } from '@supabase/ssr';
import { jsPDF } from "jspdf";
import html2canvas from 'html2canvas';

type Tab = "analyze" | "history" | "pricing";

export default function Home() {
  const [supabase] = useState(() => createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  ));

  const [user, setUser] = useState<any>(null);
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState("");
  const [language, setLanguage] = useState("EN");
  const [authChecking, setAuthChecking] = useState(true);
  const [activeTab, setActiveTab] = useState<Tab>("analyze");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  // Renkler scale simgesiyle uyumlu ve arka planla dengeli olacak şekilde ayarlanmıştır. 
  const gold = "#c7b079"; // yeni logo altın tınısı
  const darkBlue = "#182332"; // görselin arka planındaki gerçek ton
  const midBlue = "#232d3c"; // görselin iç halka tonu
  const accentBlue = "#233c58"; // secondary vurgu

  const languages = ["TR", "EN", "DE", "RU", "ZH", "AR", "FR", "ES"];

// UI object only once; keep below

  
  const ui: any = {
    TR: { title: "VERITAS LEGAL AI", sub: "YÜKSEK HUKUK ANALİTİĞİ", btn: "ANALİZİ BAŞLAT", logout: "Güvenli Çıkış", googleBtn: "Google ile Giriş Yap", upload: "PDF Belgesini Sürükleyin veya Seçin", select: "Dosya Seç", uploadLimit: "100 taneye kadar PDF yükleyebilirsiniz.",
    sidebar_analyze: "Analiz", sidebar_history: "Geçmiş", sidebar_pricing: "Paketler",
freeAnalysis: "Her kullanıcı için ilk analiz ücretsizdir. Sonrasında paket satın almanız gerekir.", processing: "YAPAY ZEKA ANALİZ EDİYOR...", download: "RESMİ RAPORU İNDİR (.PDF)", ready: "● Belge Hazır",
      reportTitles: [
        "📋 Veritas AI Analiz Raporu",
        "1. Analiz Özeti (Executive Summary)",
        "Olayın Özeti:",
        "Hukuki Nitelendirme:",
        "2. İlgili Mevzuat Dayanakları (Legal Basis)",
        "Kanun Maddeleri:",
        "Yönetmelik & Tebliğler:",
        "3. Güncel İçtihatlar ve Yargıtay Kararları (Precedents)",
        "Emsal Kararlar:",
        "Karar Analizi:",
        "4. Hukuki Risk ve Fırsat Analizi (Risk Assessment)",
        "Güçlü Yönler:",
        "Zayıf Yönler/Riskler:",
        "5. Stratejik Öneriler ve Yol Haritası (Recommendations)",
        "Atılması Gereken Adımlar:",
        "Zamanaşımı Uyarıları:",
        "6. Sonuç ve Değerlendirme (Conclusion)",
        "Yasal Uyarı: Bu rapor Veritas AI tarafından mevzuat ve içtihatlar ışığında otomatik olarak oluşturulmuştur. Bir avukatın nihai incelemesi yerine geçmez; yalnızca ön bilgilendirme amaçlıdır."
      ]
    },
    EN: { title: "VERITAS LEGAL AI", sub: "SUPREME LEGAL ANALYTICS", btn: "START ANALYSIS", logout: "Logout", googleBtn: "Sign in with Google", upload: "Drop or Select PDF Document", select: "Select File", uploadLimit: "You can upload up to 100 PDF files.",
    sidebar_analyze: "Analyze", sidebar_history: "History", sidebar_pricing: "Pricing",
freeAnalysis: "Each user gets 1 free PDF analysis. For additional analyses, please purchase a plan.", processing: "AI IS ANALYZING...", download: "DOWNLOAD OFFICIAL REPORT (.PDF)", ready: "● File Ready",
      reportTitles: [
        "📋 Veritas AI Analysis Report",
        "1. Executive Summary",
        "Summary of Facts:",
        "Legal Qualification:",
        "2. Legal Basis",
        "Statutes/Articles:",
        "Regulations:",
        "3. Recent Precedents and Case Law",
        "Precedents:",
        "Decision Analysis:",
        "4. Legal Risk and Opportunity Assessment",
        "Strengths:",
        "Weaknesses / Risks:",
        "5. Strategic Suggestions and Roadmap",
        "Recommended Actions:",
        "Limitation Warnings:",
        "6. Conclusion",
        "Disclaimer: This report was automatically generated by Veritas AI in light of legislation and precedents. It is not a substitute for an attorney’s final review; for preliminary information only."
      ]
    },DE: { title: "VERITAS LEGAL AI", sub: "RECHTSANALYSE AUF HÖCHSTEM NIVEAU", btn: "ANALYSE STARTEN", logout: "Sicher abmelden", googleBtn: "Mit Google anmelden", upload: "PDF-Dokument auswählen oder ablegen", select: "Datei auswählen", uploadLimit: "Sie können bis zu 100 PDF-Dateien hochladen.",
    sidebar_analyze: "Analyse", sidebar_history: "Verlauf", sidebar_pricing: "Pakete",
processing: "KI ANALYSIERT...", download: "OFFIZIELLEN BERICHT HERUNTERLADEN (.PDF)" },
    RU: { title: "VERITAS LEGAL AI", sub: "ПРАВОВОЙ АНАЛИТИКА НА ВЫСШЕМ УРОВНЕ", btn: "НАЧАТЬ АНАЛИЗ", logout: "Безопасный выход", googleBtn: "Войти через Google", upload: "Перетащите или выберите PDF-файл", select: "Выбрать файл", uploadLimit: "Вы можете загрузить до 100 PDF-файлов.",
    sidebar_analyze: "Анализ", sidebar_history: "История", sidebar_pricing: "Тарифы",
processing: "ИИ АНАЛИЗИРУЕТ...", download: "СКАЧАТЬ ОФИЦИАЛЬНЫЙ ОТЧЕТ (.PDF)" },
    ZH: { title: "VERITAS LEGAL AI", sub: "法律分析", btn: "开始分析", logout: "登出", googleBtn: "使用 Google 登录", upload: "拖放或选择 PDF 文件", select: "选择文件", uploadLimit: "您最多可以上传100个PDF文件。",
    sidebar_analyze: "分析", sidebar_history: "历史", sidebar_pricing: "套餐",
processing: "系统分析中...", download: "下载报告 (.PDF)" },
    AR: { title: "فيريتاس إيه آي", sub: "تحليل قانوني رفيع المستوى", btn: "بدء التحليل", logout: "تسجيل خروج آمن", googleBtn: "تسجيل الدخول باستخدام Google", upload: "أفلت أو اختر ملف PDF", select: "اختر ملف", uploadLimit: "يمكنك تحميل ما يصل إلى 100 ملف PDF.",
    sidebar_analyze: "تحليل", sidebar_history: "السجل", sidebar_pricing: "الباقات",
processing: "يجري التحليل بالذكاء الاصطناعي...", download: "تحميل التقرير الرسمي (.PDF)" },
    FR: { title: "VERITAS LEGAL AI", sub: "ANALYSE JURIDIQUE SUPÉRIEURE", btn: "DÉMARRER L'ANALYSE", logout: "Déconnexion sécurisée", googleBtn: "Connexion via Google", upload: "Déposer ou sélectionner un document PDF", select: "Sélectionner le fichier", uploadLimit: "Vous pouvez télécharger jusqu'à 100 fichiers PDF.",
    sidebar_analyze: "Analyser", sidebar_history: "Historique", sidebar_pricing: "Abonnements",
processing: "L'IA ANALYSE...", download: "TÉLÉCHARGER LE RAPPORT OFFICIEL (.PDF)" },
    ES: { title: "VERITAS LEGAL AI", sub: "ANÁLISIS LEGAL SUPREMO", btn: "INICIAR ANÁLISIS", logout: "Cerrar sesión", googleBtn: "Iniciar sesión con Google", upload: "Arrastra o selecciona un documento PDF", select: "Seleccionar archivo", uploadLimit: "Puede subir hasta 100 archivos PDF.",
    sidebar_analyze: "Analizar", sidebar_history: "Historial", sidebar_pricing: "Planes",
processing: "La IA está analizando...", download: "DESCARGAR INFORME OFICIAL (.PDF)" },
  };


  useEffect(() => {
    const initAuth = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      setUser(session?.user ?? null);
      setAuthChecking(false);
    };
    initAuth();
  }, [supabase]);

  const handleAuth = async () => {
    await supabase.auth.signInWithOAuth({
      provider: 'google',
      options: { redirectTo: `${window.location.origin}/auth/callback` }
    });
  };

  const handleAnalyze = async () => {
    if (!file || !user) return;
    setLoading(true);
    setResult("");
    // Extra log
    console.log('Analiz başlatıldı:', { file, language });
    try {
      const pdfjs = await import('pdfjs-dist');
      pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
      const arrayBuffer = await file.arrayBuffer();
      const pdf = await pdfjs.getDocument({ data: arrayBuffer }).promise;
      let text = "";
      for (let i = 1; i <= Math.min(pdf.numPages, 100); i++) {
        const page = await pdf.getPage(i);
        const content = await page.getTextContent();
        text += (content.items as any[]).map((item) => item.str).join(" ") + "\n";
      }
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pdfText: text, targetLang: language })
      });
      const data = await res.json();
      setResult(data.reply);
    } catch (err) {
      setResult("Hata oluştu: " + (err instanceof Error ? err.message : JSON.stringify(err)));
      console.error('Analiz Hatası:', err);
    } finally { setLoading(false); }
  };

  const downloadPDF = async () => {
    if (!reportRef.current) return;
    const canvas = await html2canvas(reportRef.current, { scale: 2, backgroundColor: "#020617" });
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    pdf.addImage(imgData, 'PNG', 0, 0, 210, (canvas.height * 210) / canvas.width);
    pdf.save("Veritas_Report.pdf");
  };

  if (authChecking) return null;

  // --- AI raporunu property-JSON olarak ayırmak için RAPOR PARSING KISMI ---
  let parsedResult: any = null;
  try { if (typeof result == 'string' && result.trim().startsWith('{')) parsedResult = JSON.parse(result); } catch {}
  const r = parsedResult || {};

  return (
    <>
      {/* DİL SEÇİCİ GLOBAL EN ÜSTTE */}
      <div style={{ width: '100vw', textAlign:'center', background: 'rgba(23,24,35,0.95)', padding: 7, position: 'fixed', top: 0, left: 0, zIndex: 999, display:'flex', alignItems:'center', justifyContent:'center', gap:12 }}>
        <a href="/" style={{marginRight:8, display:'inline-flex', alignItems:'center', justifyContent:'center', height:32, width:32}} aria-label="Anasayfa">
  <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke={gold} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{verticalAlign:'middle', display:'block'}}>
    <path d="M3 10.5L12 4l9 6.5V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V10.5z" fill="#181f3a"/>
    <path d="M9 22V12h6v10" fill="none"/></svg>
</a>
        {languages.map(lang => (
          <button key={lang} onClick={() => setLanguage(lang)} style={{ background: language === lang ? gold : 'rgba(212, 175, 55, 0.1)', color: language === lang ? '#181f3a' : gold, border: `1px solid ${gold}`, padding: '2px 8px', borderRadius: '13px', cursor: 'pointer', fontSize: '0.97rem', fontWeight: 600, margin: 1, transition: 'all 0.25s', outline: language === lang ? `2px solid ${gold}` : 'none', minWidth: 34, minHeight: 28, opacity: language===lang?1:0.83 }}>{lang}</button>
        ))}
      </div>
      <button
        onClick={() => setSidebarOpen(v => !v)}
        style={{
          position: 'fixed', top: 16, left: 16, zIndex: 1200,
          background: darkBlue + 'e6',
          border: 'none', borderRadius: 10, width: 44, height: 44,
          display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
          boxShadow: '0 2px 16px #0009'
        }}
        aria-label={sidebarOpen ? "Menüyü Gizle" : "Menüyü Aç"}
      >
        <span style={{ fontSize: 29, color: gold, fontWeight: 800 }}>☰</span>
      </button>
      <div style={{ minHeight: '100vh', backgroundColor: darkBlue, color: '#f8fafc', display: 'flex', flexDirection: 'row', alignItems: 'stretch', paddingTop: 60 }}>


      {/* Sidebar - Gold Glassmorphism */}
      {sidebarOpen && (
        <aside style={{ width: 270, background: darkBlue + 'ed', borderRight: `1.5px solid ${gold}ae`, boxShadow: `8px 0 40px ${midBlue}99`, display: 'flex', flexDirection: 'column', alignItems: 'center', position: 'relative', padding: '36px 0', minHeight: '100vh', zIndex: 1100 }}>

        <div style={{ fontSize: '2.2rem', color: gold, marginBottom: 16, fontWeight: 'bold', letterSpacing: 2, textShadow: `0 0 12px ${gold}77` }}>⚖️ VERITAS</div>
        <div style={{ width: '140px', height: '1px', background: `linear-gradient(to right, transparent, ${gold}, transparent)` }} />
        <div style={{ fontFamily: 'serif', color: '#ccd6f6', margin: '18px 0 2rem', fontSize: '0.81rem', fontWeight: 600, letterSpacing: 1, opacity: 0.6 }}>{ui[language].sub}</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', width: '90%', marginBottom: 45 }}>
          <button onClick={() => setActiveTab('analyze')} style={{padding: '13px 0', background: activeTab==='analyze' ? gold : 'none', color: activeTab==='analyze' ? '#1e222e' : gold, fontWeight: 800, fontSize: '1.01rem', border: 'none', borderRadius: '18px', cursor: 'pointer', boxShadow: activeTab==='analyze' ? `0 0 14px ${gold}42` : 'none', transition: 'all .25s' }}>🔎 {ui[language]?.sidebar_analyze || 'Analiz'}</button>
          <button onClick={() => setActiveTab('history')} style={{padding: '13px 0', background: activeTab==='history' ? gold : 'none', color: activeTab==='history' ? '#1e222e' : gold, fontWeight: 800, fontSize: '1.01rem', border: 'none', borderRadius: '18px', cursor: 'pointer', boxShadow: activeTab==='history' ? `0 0 14px ${gold}42` : 'none', transition: 'all .25s' }}>📜 {ui[language]?.sidebar_history || 'Geçmiş'}</button>
          <button onClick={() => setActiveTab('pricing')} style={{padding: '13px 0', background: activeTab==='pricing' ? gold : 'none', color: activeTab==='pricing' ? '#1e222e' : gold, fontWeight: 800, fontSize: '1.01rem', border: 'none', borderRadius: '18px', cursor: 'pointer', boxShadow: activeTab==='pricing' ? `0 0 14px ${gold}42` : 'none', transition: 'all .25s' }}>💳 {ui[language]?.sidebar_pricing || 'Paketler'}</button>
        </div>
        <div style={{ position: 'absolute', bottom: 28, width: '90%' }}>
          <hr style={{ borderColor: `${gold}22` }} />
          <div style={{ color: '#ffe18d', fontSize: '0.81rem', textAlign: 'center', opacity: 0.45, marginTop: 12 }}>
            Veritas Elite SaaS © 2025<br />Powered by OpenAI</div>
        </div>
      </aside>
      )}
      

      {/* Content Area (right) */}
      <main style={{ flex: 1, padding: '24px 0', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-start', overflowY: 'auto' }}>
        {/* Full-screen Hero - login öncesi gösterilecek! */}
        {!user && !authChecking && (
          <div style={{ width: '100vw', minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'radial-gradient(circle at 50% 10%, #222b50 0%, #020617 90%)', position: 'fixed', top: 0, left: 0, zIndex: 10 }}>
            <div style={{ background: 'rgba(29,36,65,0.80)', boxShadow: `0 6px 60px #0f182a88`, borderRadius: 40, padding: '70px 55px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 40 }}>
              <img 
  src="/logoverl.png" 
  alt="Veritas AI Logo" 
  style={{ width: '250px', height: 'auto', display: 'block', margin: '0 auto' }} 
/>
              <div style={{ color: gold, fontSize: '2rem', letterSpacing: 4, fontWeight: 900, textShadow: `0 0 18px ${gold}88`, marginTop: 8 }}>{ui[language].title}</div>
              <div style={{ color: '#cbd5e1', fontSize: '1.17rem', fontWeight: 600, marginBottom: 10, letterSpacing: '2.5px', textAlign: 'center' }}>{ui[language].sub}</div>
              <button onClick={handleAuth} style={{  display: 'inline-flex', alignItems: 'center', gap: 16, padding: '20px 48px', background: 'white', color: '#222b50', fontWeight: '900', borderRadius: '22px', border: 'none', cursor: 'pointer', fontSize: '1.22rem', letterSpacing: 2, boxShadow: `0 8px 22px ${gold}33`, transition: 'all .2s' }}>
                <img src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg" alt="Google" style={{ width: '28px', borderRadius: '5px' }}/> {ui[language].googleBtn}
              </button>
            </div>
          </div>
        )}

        {/* TAB İÇERİKLERİ */}
        {user && !authChecking && (
          activeTab === "analyze"
          ? (<div style={{ width: '100%', maxWidth: 820, margin: '0 auto', marginTop: 32 }}>
            <img 
  src="/logoverl.png" 
  alt="Veritas AI Logo" 
  style={{ width: '250px', height: 'auto', display: 'block', margin: '0 auto' }} 
/>
            <div style={{ background: midBlue+'77', padding: '50px', borderRadius: '35px', border: `2px dashed ${gold}44`, textAlign: 'center', transition: 'all 0.3s', position: 'relative', overflow: 'hidden' }}>
              <input
                type="file"
                id="fileUpload"
                accept=".pdf"
                onChange={(e) => setFile(e.target.files?.[0] || null)}
                style={{ display: 'none' }}
              />
              <button
                type="button"
                style={{
                  background: gold,
                  color: '#181f3a',
                  border: 'none',
                  borderRadius: 9,
                  padding: '12px 28px',
                  fontWeight: 700,
                  fontSize: '1.06rem',
                  cursor: 'pointer',
                  boxShadow: `0 2px 10px ${gold}22`,
                  margin: 4
                }}
                onClick={() => document.getElementById('fileUpload')?.click()}
              >
                {ui[language]?.select || 'Dosya Seç'}
              </button>
                  <div style={{ fontSize: '3.5rem', marginBottom: '20px', filter: 'grayscale(0.5)' }}>📂</div>
                  <div style={{ color: gold, fontSize: '1.2rem', fontWeight: 'bold', marginBottom: '10px' }}>
                    {file ? file.name : ui[language].upload}
                  </div>
                  <div style={{ color: '#ffe18d', fontSize: '.91rem', fontWeight: 600, margin: '5px 0 0 0', opacity:.77 }}>
                    {ui[language]?.uploadLimit}
                  </div>
                  <div style={{ color: '#71e0b4', fontSize: '.92rem', fontWeight: 700, marginBottom: 7, marginTop: 3, opacity: .94 }}>
                    {ui[language]?.freeAnalysis}
                  </div>
              {file && <div style={{ color: '#10b981', fontSize: '0.8rem' }}>{ui[language].ready}</div>}

{result && (
      <div ref={reportRef} style={{ background: '#020617', padding: '60px', borderRadius: '14px', borderLeft: `10px solid ${gold}`, boxShadow: '0 0 60px rgba(0,0,0,0.8)', position: 'relative', marginTop: 32, color: '#f1efca', fontSize: '1.13rem', lineHeight: 1.8 }}>
        <div style={{ color: gold, fontSize: '2.4rem', fontWeight: 900, marginBottom: 32, letterSpacing: 1.2, textShadow:'0 3px 14px #000b' }}>{ui[language].reportTitles[0]}</div>
        <div style={{margin:'22px 0'}}>
          <div style={{ fontWeight: 900, color:'#ffe18d', margin:'26px 0 12px 0', fontSize:'1.42rem', letterSpacing:'.04em', textShadow:'0 1px 4px #000b' }}>{ui[language].reportTitles[1]}</div>
          <strong>{ui[language].reportTitles[2]}</strong> {r.summary ?? (typeof result === 'string' ? result : '-') }<br/>
          <strong>{ui[language].reportTitles[3]}</strong> {r.qualification ?? '-'}
    </div>
    <div style={{margin:'22px 0'}}>
      <div style={{ fontWeight: 900, color:'#ffe18d', margin:'26px 0 12px 0', fontSize:'1.42rem', letterSpacing:'.04em', textShadow:'0 1px 4px #000b' }}>{ui[language].reportTitles[4]}</div>
      <strong>{ui[language].reportTitles[5]}</strong><br/>{r.articles ?? '-'}
      <br/><strong>{ui[language].reportTitles[6]}</strong><br/>{r.regulations ?? '-'}
    </div>
    <div style={{margin:'22px 0'}}>
      <div style={{ fontWeight: 900, color:'#ffe18d', margin:'26px 0 12px 0', fontSize:'1.42rem', letterSpacing:'.04em', textShadow:'0 1px 4px #000b' }}>{ui[language].reportTitles[7]}</div>
      <strong>{ui[language].reportTitles[8]}</strong><br/>{r.precedents ?? '-'}
      <br/><strong>{ui[language].reportTitles[9]}</strong><br/>{r.precedentAnalysis ?? '-'}
    </div>
    <div style={{margin:'22px 0'}}>
      <div style={{ fontWeight: 900, color:'#ffe18d', margin:'26px 0 12px 0', fontSize:'1.42rem', letterSpacing:'.04em', textShadow:'0 1px 4px #000b' }}>{ui[language].reportTitles[10]}</div>
      <strong>{ui[language].reportTitles[11]}</strong><br/>{r.strengths ?? '-'}
      <br/><strong>{ui[language].reportTitles[12]}</strong><br/>{r.weaknesses ?? '-'}
    </div>
    <div style={{margin:'22px 0'}}>
      <div style={{ fontWeight: 900, color:'#ffe18d', margin:'26px 0 12px 0', fontSize:'1.42rem', letterSpacing:'.04em', textShadow:'0 1px 4px #000b' }}>{ui[language].reportTitles[13]}</div>
      <strong>{ui[language].reportTitles[14]}</strong><br/>{r.recommendations ?? '-'}
      <br/><strong>{ui[language].reportTitles[15]}</strong><br/>{r.limitationWarnings ?? '-'}
    </div>
    <div style={{margin:'22px 0'}}>
      <div style={{ fontWeight: 900, color:'#ffe18d', margin:'26px 0 12px 0', fontSize:'1.42rem', letterSpacing:'.04em', textShadow:'0 1px 4px #000b' }}>{ui[language].reportTitles[16]}</div>
      {r.conclusion ?? '-'}
    </div>
    <div style={{marginTop:36, borderTop:'1px dashed #ffe18d88', paddingTop:20, fontSize:'.96rem', color:'#ffcf7e'}}>
      <b>{ui[language].reportTitles[17]}</b>
    </div>
              </div>
)}
              <button 
                onClick={handleAnalyze}
                disabled={!file || loading}
              style={{
                width: '100%',
                padding: '22px',
                background: file ? `linear-gradient(45deg, ${gold}, #fef3c7)` : '#1e293b',
                color: file ? '#000' : '#475569',
                fontWeight: '900',
                borderRadius: '20px',
                border: 'none',
                cursor: file ? 'pointer' : 'not-allowed',
                fontSize: '1.2rem',
                letterSpacing: '2px',
                boxShadow: file ? `0 15px 35px ${gold}33` : 'none',
                transition: '0.4s',
                marginTop: 26,
                marginBottom: 10
              }}
              >
                {loading ? ui[language].processing : ui[language].btn}
              </button>
          </div>
          </div>)
          : activeTab === "pricing"
          ? (
          <div style={{ width: '100%', maxWidth: 790, margin: '0 auto', marginTop: 22 }}>
            <div style={{
              border: `2px solid ${gold}66`, background: 'rgba(24,33,60,0.18)', borderRadius: '25px', boxShadow: `0 4px 40px ${gold}19`, padding: 38, textAlign: 'center', color: gold, fontWeight: 900, fontSize: 30, letterSpacing: 1.2, marginBottom: 18
            }}>
              Elite Paketler / Elite Pricing
            </div>
            <div style={{ display: 'flex', gap: 24, justifyContent: 'center', alignItems: 'flex-end', flexWrap: 'wrap' }}>
                {(language === "TR" || (typeof navigator !== 'undefined' && navigator.language?.toLowerCase().startsWith('tr')))
                ? <>
                  <PricingCard gold={gold} plan="Basic" price="49₺ / ay"
                    features={["Bireysel kullanıcı, küçük ofis", "Ayda 10 analiz"]}/>
                  <PricingCard gold={gold} plan="Professional" price="149₺ / ay" popular
                    features={["Avukat, KOBİ, danışmanlık ofisi, ajans", "Ayda 50 analiz", "PDF/Word olarak indirme"]}/>
                  <PricingCard gold={gold} plan="Elite" price="399₺ / ay"
                    features={["Büyük ofis, sektör lideri, kurumsal", "Sınırsız analiz", "PDF/Word olarak indirme, Geçmiş kaydı"]}/>
                </>
                : <>
                  <PricingCard gold={gold} plan="Basic" price="$29 / mo"
                    features={["Individual user, small office", "10 analyses/month"]}/>
                  <PricingCard gold={gold} plan="Professional" price="$79 / mo" popular
                    features={["Frequent analysis, lawyer/SME/agency", "50 analyses/month", "PDF/Word export"]}/>
                  <PricingCard gold={gold} plan="Elite" price="$199 / mo"
                    features={["Large office, enterprise", "Unlimited analyses", "PDF/Word export, Save history"]}/>
                </>
                }
              </div>
            </div>
          )
          : null
        )}
        <style jsx global>{`
          @keyframes fadeInDown { from { opacity: 0; transform: translateY(-20px); } to { opacity: 1; transform: translateY(0); } }
          @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
          button:hover { filter: brightness(1.1); transform: translateY(-2px); }
        `}</style>
      </main>
    </div>
    <footer
      style={{
        width: '100vw',
        textAlign: 'center',
        padding: '22px 0 18px 0',
        background: 'rgba(30,38,58,0.08)',
        fontSize: '.97rem',
        color: '#a5acc9',
        fontWeight: 500,
        letterSpacing: '.01em',
        borderTop: '1px solid #242849',
        marginTop: 40
      }}
    >
      <a
        href="/kvkk"
        target="_blank"
        rel="noopener noreferrer"
        style={{ color: '#ffe18d', textDecoration: 'underline', marginRight: 22 }}
      >
        {language === "TR" ? "KVKK Aydınlatma Metni" : "GDPR / Data Privacy Notice"}
      </a>
      <a
        href="/privacy"
        target="_blank"
        rel="noopener noreferrer"
        style={{ color: '#ffe18d', textDecoration: 'underline', marginRight: 22 }}
      >
        {language === "TR" ? "Gizlilik Sözleşmesi" : "Privacy Policy"}
      </a>
      <a
        href="/distance-agreement"
        target="_blank"
        rel="noopener noreferrer"
        style={{ color: '#ffe18d', textDecoration: 'underline' }}
      >
        {language === "TR" ? "Mesafeli Satış Sözleşmesi" : "Distance Sales Agreement"}
      </a>
    </footer>
    </>
  );
}