import { getLanguage, type Language } from './translations';

const componentTranslations: Record<Language, Record<string, string>> = {
  TR: {
    betaMessage: 'Veritas Q-AI Beta: Hata bul, bildir ve Professional pakette %50 indirim kazan!', reportBug: 'Hata Bildir', close: 'Kapat',
    aboutDescription: 'Veritas Legal AI, hukuk profesyonelleri için belgeleri saniyeler içinde analiz eden gelişmiş bir yapay zeka sistemidir.', back: 'Geri Dön',
    comparisonResults: 'Dosya Karşılaştırma Sonuçları', crossLanguageComparison: 'Çapraz Dil Karşılaştırması (Quantum Global)', document1: 'İlk Dosya:', document2: 'İkinci Dosya:', detectedDifferences: 'Tespit Edilen Farklar', section: 'Madde/Bölüm', changeType: 'Değişiklik Tipi', riskImpact: 'Risk Etkisi', description: 'Açıklama', detailedComparisonReport: 'Detaylı Karşılaştırma Raporu',
    feedbackHub: 'İstek & Öneri', feedbackIntro: "Veritas Q-AI'da ne görmek istersiniz? (Yeni ülkeler, daha hızlı analiz, özel hukuk araçları...)", thankYou: 'Teşekkürler!', feedbackSuccess: 'Öneriniz ekibimize iletildi. Geri bildiriminiz için teşekkürler!', emailOptional: 'E-posta (Opsiyonel)', emailReason: '- Dönüş yapabilmemiz için', suggestionIdea: 'Öneri / Düşünce *', suggestionPlaceholder: 'Örneğin: "Fransa hukuku desteği eklenebilir mi?" veya "Analiz süresini kısaltmak için..."', sending: 'Gönderiliyor...', sendDevelopers: 'Geliştiricilere Gönder', enterSuggestion: 'Lütfen önerinizi girin.', feedbackSubmitError: 'Öneri gönderilirken bir sorun oluştu.'
  },
  EN: {
    betaMessage: 'Veritas Q-AI Beta: Find bugs, report them and get 50% off the Professional package!', reportBug: 'Report Bug', close: 'Close',
    aboutDescription: 'Veritas Legal AI is an advanced artificial intelligence system that analyzes documents for legal professionals in seconds.', back: 'Back', comparisonResults: 'Document Comparison Results', crossLanguageComparison: 'Cross-Language Comparison (Quantum Global)', document1: 'Document 1:', document2: 'Document 2:', detectedDifferences: 'Detected Differences', section: 'Section', changeType: 'Change Type', riskImpact: 'Risk Impact', description: 'Description', detailedComparisonReport: 'Detailed Comparison Report',
    feedbackHub: 'Feedback Hub', feedbackIntro: 'What would you like to see in Veritas Q-AI? (New countries, faster analysis, specific legal tools...)', thankYou: 'Thank You!', feedbackSuccess: 'Thank you! Your suggestion has been sent to our core team.', emailOptional: 'Email (Optional)', emailReason: '- So we can get back to you', suggestionIdea: 'Suggestion / Idea *', suggestionPlaceholder: 'E.g., "Can you add France legal support?" or "To speed up analysis..."', sending: 'Sending...', sendDevelopers: 'Send to Developers', enterSuggestion: 'Please enter your suggestion.', feedbackSubmitError: 'An error occurred while submitting your suggestion.'
  },
  DE: {
    betaMessage: 'Veritas Q-AI Beta: Fehler finden, melden und 50 % Rabatt auf das Professional-Paket erhalten!', reportBug: 'Fehler melden', close: 'Schließen',
    aboutDescription: 'Veritas Legal AI ist ein fortschrittliches KI-System, das Dokumente für Rechtsexperten in Sekundenschnelle analysiert.', back: 'Zurück', comparisonResults: 'Ergebnisse des Dokumentvergleichs', crossLanguageComparison: 'Sprachübergreifender Vergleich (Quantum Global)', document1: 'Dokument 1:', document2: 'Dokument 2:', detectedDifferences: 'Erkannte Unterschiede', section: 'Abschnitt', changeType: 'Änderungstyp', riskImpact: 'Risikoauswirkung', description: 'Beschreibung', detailedComparisonReport: 'Detaillierter Vergleichsbericht',
    feedbackHub: 'Feedback & Vorschläge', feedbackIntro: 'Was möchten Sie in Veritas Q-AI sehen? (Neue Länder, schnellere Analysen, spezielle Rechtswerkzeuge ...)', thankYou: 'Vielen Dank!', feedbackSuccess: 'Ihr Vorschlag wurde an unser Team weitergeleitet. Vielen Dank für Ihr Feedback!', emailOptional: 'E-Mail (optional)', emailReason: '- Damit wir Sie kontaktieren können', suggestionIdea: 'Vorschlag / Idee *', suggestionPlaceholder: 'Z. B. „Können Sie französisches Recht unterstützen?“ oder „Um die Analyse zu beschleunigen ...“', sending: 'Wird gesendet...', sendDevelopers: 'An die Entwickler senden', enterSuggestion: 'Bitte geben Sie Ihren Vorschlag ein.', feedbackSubmitError: 'Beim Senden Ihres Vorschlags ist ein Fehler aufgetreten.'
  },
  FR: {
    betaMessage: 'Veritas Q-AI Beta : trouvez et signalez des bugs et obtenez 50 % de réduction sur le forfait Professional !', reportBug: 'Signaler un bug', close: 'Fermer',
    aboutDescription: 'Veritas Legal AI est un système avancé d’intelligence artificielle qui analyse en quelques secondes des documents pour les professionnels du droit.', back: 'Retour', comparisonResults: 'Résultats de la comparaison des documents', crossLanguageComparison: 'Comparaison multilingue (Quantum Global)', document1: 'Document 1 :', document2: 'Document 2 :', detectedDifferences: 'Différences détectées', section: 'Section', changeType: 'Type de modification', riskImpact: 'Impact sur le risque', description: 'Description', detailedComparisonReport: 'Rapport de comparaison détaillé',
    feedbackHub: 'Avis & Suggestions', feedbackIntro: 'Que souhaitez-vous voir dans Veritas Q-AI ? (Nouveaux pays, analyse plus rapide, outils juridiques spécialisés...)', thankYou: 'Merci !', feedbackSuccess: 'Votre suggestion a été transmise à notre équipe. Merci pour votre retour !', emailOptional: 'E-mail (facultatif)', emailReason: '- Pour que nous puissions vous répondre', suggestionIdea: 'Suggestion / Idée *', suggestionPlaceholder: 'Ex. : « Pouvez-vous ajouter le droit français ? » ou « Pour accélérer l’analyse... »', sending: 'Envoi en cours...', sendDevelopers: 'Envoyer aux développeurs', enterSuggestion: 'Veuillez saisir votre suggestion.', feedbackSubmitError: 'Une erreur est survenue lors de l’envoi de votre suggestion.'
  }
};

export function ct(language: string, key: string): string {
  const lang = getLanguage(language);
  return componentTranslations[lang]?.[key] ?? componentTranslations.EN[key] ?? key;
}
