import { getLanguage, type Language } from './translations';

const componentTranslations: Record<Language, Record<string, string>> = {
  TR: {
    betaMessage: 'Veritas Q-AI Beta: Hata bul, bildir ve Professional pakette %50 indirim kazan!', reportBug: 'Hata Bildir', close: 'Kapat',
    aboutDescription: 'Veritas Legal AI, hukuk profesyonelleri için belgeleri saniyeler içinde analiz eden gelişmiş bir yapay zeka sistemidir.', back: 'Geri Dön',
    comparisonResults: 'Dosya Karşılaştırma Sonuçları', crossLanguageComparison: 'Çapraz Dil Karşılaştırması (Quantum Global)', document1: 'İlk Dosya:', document2: 'İkinci Dosya:', detectedDifferences: 'Tespit Edilen Farklar', section: 'Madde/Bölüm', changeType: 'Değişiklik Tipi', riskImpact: 'Risk Etkisi', description: 'Açıklama', detailedComparisonReport: 'Detaylı Karşılaştırma Raporu',
    feedbackHub: 'İstek & Öneri', feedbackIntro: "Veritas Q-AI'da ne görmek istersiniz? (Yeni ülkeler, daha hızlı analiz, özel hukuk araçları...)", thankYou: 'Teşekkürler!', feedbackSuccess: 'Öneriniz ekibimize iletildi. Geri bildiriminiz için teşekkürler!', emailOptional: 'E-posta (Opsiyonel)', emailReason: '- Dönüş yapabilmemiz için', suggestionIdea: 'Öneri / Düşünce *', suggestionPlaceholder: 'Örneğin: "Fransa hukuku desteği eklenebilir mi?" veya "Analiz süresini kısaltmak için..."', sending: 'Gönderiliyor...', sendDevelopers: 'Geliştiricilere Gönder', enterSuggestion: 'Lütfen önerinizi girin.', feedbackSubmitError: 'Öneri gönderilirken bir sorun oluştu.',
    fileTooLarge: 'Dosya boyutu çok büyük. Maksimum 50MB olmalıdır. (Mevcut: {size}MB)', enterBugTitle: 'Lütfen hata başlığı girin.', enterBugDescription: 'Lütfen hata açıklaması girin.', bugSubmitError: 'Hata bildirimi gönderilirken bir sorun oluştu.', bugSuccess: 'Harika! Hata raporun alındı. Beta sürecine katkın için teşekkürler. İncelememizden sonra Professional pakette geçerli VERITAS50 kodunu ödeme ekranında kullanabilirsin!', discountProfessional: 'Professional Paket için %50 İndirim', bugTitle: 'Hata Başlığı *', bugTitlePlaceholder: 'Örn: Giriş sayfasında buton çalışmıyor', bugDescription: 'Hata Açıklaması *', bugDescriptionPlaceholder: 'Hatanın ne olduğunu ve nasıl oluştuğunu açıklayın...', fileAttachment: 'Dosya Eki (Opsiyonel - Maks. 50MB)', remove: 'Kaldır', cancel: 'İptal', uploadingFile: 'Dosya Yükleniyor...', submitting: 'Gönderiliyor...', send: 'Gönder', previewAlt: 'Önizleme',
    credits: 'Krediler', analyze: 'Analiz', analyzeLoginRequired: 'Analiz (Giriş Gerekli)', packages: 'Paketler', history: 'Geçmiş', historyEnterpriseOnly: 'Bu özellik sadece Enterprise paketi için geçerlidir.', unlimitedAnalysis: 'Sınırsız Analiz', whatIsVeritas: 'Veritas Q-AI Nedir?', quantumLeapLaw: 'Hukukta Kuantum Sıçraması', solutionTitle: 'Ne Çözüm Sunuyoruz?', solutionText: 'Veritas Q-AI, modern hukukta karmaşıklığı azaltmak için dört büyük yargı alanındaki (TR, US, UK, DE) mevzuat ve içtihatları analiz eder ve görünmeyen hukuki riskleri ortaya çıkarmaya yardımcı olur.', technologyTitle: 'Nasıl Sunuyoruz?', technologyText: 'Hibrit Kuantum-AI mimarisi kullanıyoruz. AI katmanları küresel hukuk verilerini toplar ve yapılandırırken analiz motoru belgeniz ile mevcut hukuk kaynakları arasındaki ilişkileri değerlendirir.', valueTitle: 'Neden Veritas?', value1: 'Küresel Yargı İçgörüsü: 4 ülkede eşzamanlı analiz.', value2: 'Anahtar Kelimelerin Ötesi: Hukuki mantığın bağlamsal anlaşılması.', value3: 'Risk Tahmini: Olasılık tabanlı çatışma tespiti.', liveDataPulse: 'Canlı Veri Nabzı', status: 'Durum:', quantumEngineActive: 'Kuantum Motoru Aktif', dataPool: 'Veri Havuzu:', linkedClauses: '1M+ Bağlantılı Madde', lastSync: 'Son Senkron:', realTime: 'Gerçek Zamanlı', activeJurisdictions: 'Aktif Yargı Alanları', documents: 'belge', caseLawRoulette: 'Emsal Karar Döngüsü', roiCalculator: 'ROI Hesaplayıcı', contracts: 'Sözleşme Sayısı', savings: 'Tasarruf', systemQuantumEstablished: 'Sistem Durumu: Kuantum Bağlantısı Kuruldu', riskScannedCompleted: 'Risk Taraması: Tamamlandı', databaseTooltip: 'Veritas günlük olarak 4 büyük yargı alanını tarar ve yeni yüksek mahkeme kararları ile yasal değişiklikleri tespit eder. Toplam analiz edilen kayıt: 1.2M+', lastDataSync: 'Son Veri Senkronizasyonu:', jurisdictionsCovered: 'Yargı Alanları:', requestFeature: 'İstek & Öneri'
  },
  EN: {
    betaMessage: 'Veritas Q-AI Beta: Find bugs, report them and get 50% off the Professional package!', reportBug: 'Report Bug', close: 'Close',
    aboutDescription: 'Veritas Legal AI is an advanced artificial intelligence system that analyzes documents for legal professionals in seconds.', back: 'Back', comparisonResults: 'Document Comparison Results', crossLanguageComparison: 'Cross-Language Comparison (Quantum Global)', document1: 'Document 1:', document2: 'Document 2:', detectedDifferences: 'Detected Differences', section: 'Section', changeType: 'Change Type', riskImpact: 'Risk Impact', description: 'Description', detailedComparisonReport: 'Detailed Comparison Report',
    feedbackHub: 'Feedback Hub', feedbackIntro: 'What would you like to see in Veritas Q-AI? (New countries, faster analysis, specific legal tools...)', thankYou: 'Thank You!', feedbackSuccess: 'Thank you! Your suggestion has been sent to our core team.', emailOptional: 'Email (Optional)', emailReason: '- So we can get back to you', suggestionIdea: 'Suggestion / Idea *', suggestionPlaceholder: 'E.g., "Can you add France legal support?" or "To speed up analysis..."', sending: 'Sending...', sendDevelopers: 'Send to Developers', enterSuggestion: 'Please enter your suggestion.', feedbackSubmitError: 'An error occurred while submitting your suggestion.',
    fileTooLarge: 'File size is too large. Maximum 50MB allowed. (Current: {size}MB)', enterBugTitle: 'Please enter a bug title.', enterBugDescription: 'Please enter a bug description.', bugSubmitError: 'An error occurred while submitting the bug report.', bugSuccess: 'Great! Your bug report has been received. Thanks for contributing to our Beta. You can use the code VERITAS50 at checkout for a 50% discount on the Professional plan!', discountProfessional: '50% Off on Professional Plan', bugTitle: 'Bug Title *', bugTitlePlaceholder: 'E.g., Login button not working', bugDescription: 'Bug Description *', bugDescriptionPlaceholder: 'Describe what the bug is and how it occurred...', fileAttachment: 'File Attachment (Optional - Max 50MB)', remove: 'Remove', cancel: 'Cancel', uploadingFile: 'Uploading File...', submitting: 'Submitting...', send: 'Send', previewAlt: 'Preview',
    credits: 'Credits', analyze: 'Analyze', analyzeLoginRequired: 'Analyze (Login Required)', packages: 'Packages', history: 'History', historyEnterpriseOnly: 'This feature is only available for Enterprise members.', unlimitedAnalysis: 'Unlimited Analysis', whatIsVeritas: 'What is Veritas Q-AI?', quantumLeapLaw: 'The Quantum Leap in Law', solutionTitle: 'The Solution', solutionText: 'Veritas Q-AI helps reduce the complexity of modern legal work by analyzing legislation and case law across four major jurisdictions (TR, US, UK, DE) and surfacing legal risks that might otherwise be missed.', technologyTitle: 'The Technology', technologyText: 'We use a hybrid Quantum-AI architecture. AI layers collect and structure global legal data while the analysis engine evaluates relationships between your document and current legal sources.', valueTitle: 'The Value', value1: 'Global Jurisdictional Insight: Simultaneous analysis across 4 countries.', value2: 'Beyond Keywords: Contextual understanding of legal logic.', value3: 'Risk Prediction: Probability-based conflict detection.', liveDataPulse: 'Live Data Pulse', status: 'Status:', quantumEngineActive: 'Quantum Engine Active', dataPool: 'Data Pool:', linkedClauses: '1M+ Linked Clauses', lastSync: 'Last Sync:', realTime: 'Real-time', activeJurisdictions: 'Active Jurisdictions', documents: 'documents', caseLawRoulette: 'Case-Law Roulette', roiCalculator: 'ROI Calculator', contracts: 'Contracts', savings: 'Savings', systemQuantumEstablished: 'System Status: Quantum Link Established', riskScannedCompleted: 'Risk Scanned: Completed', databaseTooltip: 'Veritas scans four major jurisdictions daily for new high-court rulings and legislative changes. Total records analyzed: 1.2M+', lastDataSync: 'Last Data Sync:', jurisdictionsCovered: 'Jurisdictions Covered:', requestFeature: 'Request a Feature / Suggestion'
  },
  DE: {
    betaMessage: 'Veritas Q-AI Beta: Fehler finden, melden und 50 % Rabatt auf das Professional-Paket erhalten!', reportBug: 'Fehler melden', close: 'Schließen',
    aboutDescription: 'Veritas Legal AI ist ein fortschrittliches KI-System, das Dokumente für Rechtsexperten in Sekundenschnelle analysiert.', back: 'Zurück', comparisonResults: 'Ergebnisse des Dokumentvergleichs', crossLanguageComparison: 'Sprachübergreifender Vergleich (Quantum Global)', document1: 'Dokument 1:', document2: 'Dokument 2:', detectedDifferences: 'Erkannte Unterschiede', section: 'Abschnitt', changeType: 'Änderungstyp', riskImpact: 'Risikoauswirkung', description: 'Beschreibung', detailedComparisonReport: 'Detaillierter Vergleichsbericht',
    feedbackHub: 'Feedback & Vorschläge', feedbackIntro: 'Was möchten Sie in Veritas Q-AI sehen? (Neue Länder, schnellere Analysen, spezielle Rechtswerkzeuge ...)', thankYou: 'Vielen Dank!', feedbackSuccess: 'Ihr Vorschlag wurde an unser Team weitergeleitet. Vielen Dank für Ihr Feedback!', emailOptional: 'E-Mail (optional)', emailReason: '- Damit wir Sie kontaktieren können', suggestionIdea: 'Vorschlag / Idee *', suggestionPlaceholder: 'Z. B. „Können Sie französisches Recht unterstützen?“ oder „Um die Analyse zu beschleunigen ...“', sending: 'Wird gesendet...', sendDevelopers: 'An die Entwickler senden', enterSuggestion: 'Bitte geben Sie Ihren Vorschlag ein.', feedbackSubmitError: 'Beim Senden Ihres Vorschlags ist ein Fehler aufgetreten.',
    fileTooLarge: 'Die Datei ist zu groß. Maximal 50 MB sind erlaubt. (Aktuell: {size} MB)', enterBugTitle: 'Bitte geben Sie einen Fehlertitel ein.', enterBugDescription: 'Bitte beschreiben Sie den Fehler.', bugSubmitError: 'Beim Senden des Fehlerberichts ist ein Problem aufgetreten.', bugSuccess: 'Ihr Fehlerbericht wurde empfangen. Vielen Dank für Ihren Beitrag zur Beta. Sie können den Code VERITAS50 beim Bezahlen für 50 % Rabatt auf den Professional-Tarif verwenden!', discountProfessional: '50 % Rabatt auf den Professional-Tarif', bugTitle: 'Fehlertitel *', bugTitlePlaceholder: 'Z. B.: Die Anmeldeschaltfläche funktioniert nicht', bugDescription: 'Fehlerbeschreibung *', bugDescriptionPlaceholder: 'Beschreiben Sie den Fehler und wie er aufgetreten ist...', fileAttachment: 'Dateianhang (optional - max. 50 MB)', remove: 'Entfernen', cancel: 'Abbrechen', uploadingFile: 'Datei wird hochgeladen...', submitting: 'Wird gesendet...', send: 'Senden', previewAlt: 'Vorschau',
    credits: 'Guthaben', analyze: 'Analyse', analyzeLoginRequired: 'Analyse (Anmeldung erforderlich)', packages: 'Pakete', history: 'Verlauf', historyEnterpriseOnly: 'Diese Funktion ist nur für Enterprise-Mitglieder verfügbar.', unlimitedAnalysis: 'Unbegrenzte Analysen', whatIsVeritas: 'Was ist Veritas Q-AI?', quantumLeapLaw: 'Der Quantensprung im Recht', solutionTitle: 'Die Lösung', solutionText: 'Veritas Q-AI hilft, die Komplexität moderner Rechtsarbeit zu reduzieren, indem Gesetzgebung und Rechtsprechung aus vier großen Rechtsordnungen (TR, US, UK, DE) analysiert und mögliche rechtliche Risiken sichtbar gemacht werden.', technologyTitle: 'Die Technologie', technologyText: 'Wir nutzen eine hybride Quantum-AI-Architektur. KI-Schichten sammeln und strukturieren globale Rechtsdaten, während die Analyse-Engine Beziehungen zwischen Ihrem Dokument und aktuellen Rechtsquellen bewertet.', valueTitle: 'Der Mehrwert', value1: 'Globale Rechtsgebiets-Einblicke: Gleichzeitige Analyse in 4 Ländern.', value2: 'Über Schlüsselwörter hinaus: Kontextuelles Verständnis rechtlicher Logik.', value3: 'Risikoprognose: Wahrscheinlichkeitsbasierte Konflikterkennung.', liveDataPulse: 'Live-Datenstatus', status: 'Status:', quantumEngineActive: 'Quantum Engine aktiv', dataPool: 'Datenpool:', linkedClauses: '1M+ verknüpfte Klauseln', lastSync: 'Letzte Synchronisierung:', realTime: 'Echtzeit', activeJurisdictions: 'Aktive Rechtsordnungen', documents: 'Dokumente', caseLawRoulette: 'Rechtsprechungs-Roulette', roiCalculator: 'ROI-Rechner', contracts: 'Verträge', savings: 'Ersparnis', systemQuantumEstablished: 'Systemstatus: Quantum-Verbindung hergestellt', riskScannedCompleted: 'Risikoscan: Abgeschlossen', databaseTooltip: 'Veritas scannt täglich vier große Rechtsordnungen auf neue höchstrichterliche Entscheidungen und Gesetzesänderungen. Analysierte Datensätze insgesamt: 1,2 Mio.+', lastDataSync: 'Letzte Datensynchronisierung:', jurisdictionsCovered: 'Abgedeckte Rechtsordnungen:', requestFeature: 'Funktion wünschen / Vorschlag'
  },
  FR: {
    betaMessage: 'Veritas Q-AI Beta : trouvez et signalez des bugs et obtenez 50 % de réduction sur le forfait Professional !', reportBug: 'Signaler un bug', close: 'Fermer',
    aboutDescription: 'Veritas Legal AI est un système avancé d’intelligence artificielle qui analyse en quelques secondes des documents pour les professionnels du droit.', back: 'Retour', comparisonResults: 'Résultats de la comparaison des documents', crossLanguageComparison: 'Comparaison multilingue (Quantum Global)', document1: 'Document 1 :', document2: 'Document 2 :', detectedDifferences: 'Différences détectées', section: 'Section', changeType: 'Type de modification', riskImpact: 'Impact sur le risque', description: 'Description', detailedComparisonReport: 'Rapport de comparaison détaillé',
    feedbackHub: 'Avis & Suggestions', feedbackIntro: 'Que souhaitez-vous voir dans Veritas Q-AI ? (Nouveaux pays, analyse plus rapide, outils juridiques spécialisés...)', thankYou: 'Merci !', feedbackSuccess: 'Votre suggestion a été transmise à notre équipe. Merci pour votre retour !', emailOptional: 'E-mail (facultatif)', emailReason: '- Pour que nous puissions vous répondre', suggestionIdea: 'Suggestion / Idée *', suggestionPlaceholder: 'Ex. : « Pouvez-vous ajouter le droit français ? » ou « Pour accélérer l’analyse... »', sending: 'Envoi en cours...', sendDevelopers: 'Envoyer aux développeurs', enterSuggestion: 'Veuillez saisir votre suggestion.', feedbackSubmitError: 'Une erreur est survenue lors de l’envoi de votre suggestion.',
    fileTooLarge: 'Le fichier est trop volumineux. La taille maximale est de 50 Mo. (Actuel : {size} Mo)', enterBugTitle: 'Veuillez saisir un titre pour le bug.', enterBugDescription: 'Veuillez décrire le bug.', bugSubmitError: 'Un problème est survenu lors de l’envoi du rapport de bug.', bugSuccess: 'Votre rapport de bug a bien été reçu. Merci de contribuer à notre bêta. Vous pouvez utiliser le code VERITAS50 lors du paiement pour obtenir 50 % de réduction sur le forfait Professional !', discountProfessional: '50 % de réduction sur le forfait Professional', bugTitle: 'Titre du bug *', bugTitlePlaceholder: 'Ex. : le bouton de connexion ne fonctionne pas', bugDescription: 'Description du bug *', bugDescriptionPlaceholder: 'Décrivez le bug et la manière dont il s’est produit...', fileAttachment: 'Pièce jointe (facultatif - max. 50 Mo)', remove: 'Supprimer', cancel: 'Annuler', uploadingFile: 'Téléversement du fichier...', submitting: 'Envoi...', send: 'Envoyer', previewAlt: 'Aperçu',
    credits: 'Crédits', analyze: 'Analyser', analyzeLoginRequired: 'Analyser (connexion requise)', packages: 'Forfaits', history: 'Historique', historyEnterpriseOnly: 'Cette fonctionnalité est réservée aux membres Enterprise.', unlimitedAnalysis: 'Analyses illimitées', whatIsVeritas: 'Qu’est-ce que Veritas Q-AI ?', quantumLeapLaw: 'Le saut quantique du droit', solutionTitle: 'La solution', solutionText: 'Veritas Q-AI aide à réduire la complexité du travail juridique moderne en analysant la législation et la jurisprudence de quatre grandes juridictions (TR, US, UK, DE) et en mettant en évidence des risques juridiques qui pourraient autrement passer inaperçus.', technologyTitle: 'La technologie', technologyText: 'Nous utilisons une architecture Quantum-AI hybride. Les couches d’IA collectent et structurent les données juridiques mondiales tandis que le moteur d’analyse évalue les relations entre votre document et les sources juridiques actuelles.', valueTitle: 'La valeur', value1: 'Vision juridique mondiale : analyse simultanée dans 4 pays.', value2: 'Au-delà des mots-clés : compréhension contextuelle de la logique juridique.', value3: 'Prévision des risques : détection probabiliste des conflits.', liveDataPulse: 'Flux de données en direct', status: 'Statut :', quantumEngineActive: 'Moteur Quantum actif', dataPool: 'Réservoir de données :', linkedClauses: '1M+ clauses liées', lastSync: 'Dernière synchro :', realTime: 'Temps réel', activeJurisdictions: 'Juridictions actives', documents: 'documents', caseLawRoulette: 'Roulette de jurisprudence', roiCalculator: 'Calculateur ROI', contracts: 'Contrats', savings: 'Économies', systemQuantumEstablished: 'État du système : liaison Quantum établie', riskScannedCompleted: 'Analyse des risques : terminée', databaseTooltip: 'Veritas analyse chaque jour quatre grandes juridictions afin de détecter de nouvelles décisions des hautes juridictions et des modifications législatives. Total des enregistrements analysés : 1,2 M+', lastDataSync: 'Dernière synchronisation des données :', jurisdictionsCovered: 'Juridictions couvertes :', requestFeature: 'Demander une fonctionnalité / Suggestion'
  }
};

export function ct(language: string, key: string, params?: Record<string, string | number>): string {
  const lang = getLanguage(language);
  let value = componentTranslations[lang]?.[key] ?? componentTranslations.EN[key] ?? key;
  if (params) {
    for (const [name, replacement] of Object.entries(params)) {
      value = value.replace(new RegExp(`\\{${name}\\}`, 'g'), String(replacement));
    }
  }
  return value;
}
