name: Daily Post
on:
  schedule:
    - cron: '0 07 * * *' # Her sabah 10:00 (TSİ)
  workflow_dispatch: # Manuel çalıştırma butonu açar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/set-up-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install google-generativeai requests
      - name: Run bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          INSTA_TOKEN: ${{ secrets.INSTA_TOKEN }}
          INSTA_ACCOUNT_ID: ${{ secrets.INSTA_ACCOUNT_ID }}
        run: python main.py
