name: Daily Post
on:
  schedule:
    - cron: '0 07 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install google-generativeai requests

      - name: Run bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          INSTA_TOKEN: ${{ secrets.INSTA_TOKEN }}
          INSTA_ACCOUNT_ID: ${{ secrets.INSTA_ACCOUNT_ID }}
        run: python main.py
        
